# Site settings
title: akonwi
email: akonwi@gmail.com
description: "My ramblings..."
baseurl: ""
url: "http://akonwi.github.io"
twitter_username: konwi7
github_username:  akonwi
google_analytics_tracking_id: UA-47544457-1

# Build settings
markdown: kramdown
permalink: /blog/:title
