# Site settings
title: akonwi
email: akonwi@gmail.com
description: "My ramblings..."
baseurl: ""
url: "http://akonwi.io"
twitter_username: konwi7
github_username:  akonwi
google_analytics_tracking_id: UA-47544457-1
gems:
  - jekyll-gist
  - rouge
# Build settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
permalink: /blog/:title
sass:
  style: compressed
